# Configuration file for MutPredpy

locations:
  local:
    mutpred2_path: "/sc/arion/projects/pejaverlab/IGVF/src/mutpred2_dev"
    catalog: "/Users/bergqt01/Research/Scratch/Testing/mutpred_catalog"
  minerva:
    mutpred2_path: "/sc/arion/projects/pejaverlab/IGVF/src/mutpred2_dev"
    catalog: "/sc/arion/projects/pejaverlab/lab_data/mutpred2"

active_location: local